### ISSUE TITLE
Timing out.

### ISSUE THREAD

**Issue by EmilKnudsen** [drtshock/Factions#361]
Hello, looks like we have some corrupt factions, when someone does /f show (corrupt faction) it times out the server. Or /f who. http://pastebin.com/Ms1hvcyZ
We're running the last version of spigot and factionsuuid. http://puu.sh/hbEeY/15ba07a4a2.png
Faction data: http://pastebin.com/x02x0iCZ
debug: true Still doesn't tell me anything in the console.
Alright so now I have been testing a lot of stuff, and this happend http://pastebin.com/muj9mGWk 
-LJGz <- Spigot.

**Comment by drtshock** [comment]
You hit the rate limit.

**Comment by EmilKnudsen** [comment]
What does that mean.

**Comment by Kakifrucht** [comment]
The Mojang API limits the amounts of UUID request to their servers. This is unrelated to Factions.

**Comment by EmilKnudsen** [comment]
So how is it possible to fix ?

**Comment by Kakifrucht** [comment]
After about one hour the rate limit should reset.

**Comment by EmilKnudsen** [comment]
So in an hour, it would reset the limit ? But how is it possible for /f show to timeout the server ?

**Comment by Kakifrucht** [comment]
When too many shows are made and the cache has no information about the players.

**Comment by EmilKnudsen** [comment]
Ah, alright. Seems legit....

**Comment by ghost** [comment]
What you are saying are not true.. i have talked to other plugin dev's and they say that this is not possible and have no rate limit..

**Comment by bobbyjoe30** [comment]
So when it does not pull users it crashes the whole server? Sounds like a great plugin.

**Comment by drtshock** [comment]
@mathiaslk then they are pretty stupid.

**Comment by EmilKnudsen** [comment]
Stupid or nah, its still not working.

**Comment by mrtortillachip** [comment]
Well can you atleast give us some tips on how to fix it

**Comment by EmilKnudsen** [comment]
We paid a sum for this plugin, and then we expect that it works, whether you have lost the interest for the plugin. At least you could guide is through this issue.

**Comment by Velociraptorclaw** [comment]
Being able to do /f show is an essential part of factions in my opinion and I urge you to come up with a fix, it is only fair to the people who paid for it.

**Comment by Kakifrucht** [comment]
/f show is not broken, however he could most likely add something to check if rate limit has been hit and then display a message to try again later.
How many people are having problems with it? I surely don't.

**Comment by EmilKnudsen** [comment]
I guess most of us have. Also, we have been waiting 1hr now. And it's still not working

**Comment by drtshock** [comment]
Your issue is with Mojang's servers. You sent too many requests and you are timing out. That is not my plugin's fault.

**Comment by EmilKnudsen** [comment]
So how do we fix the problem, that's all we're asking for.

**Comment by Ccemiza** [comment]
How is this Mojangs servers, I have been on another server and they used this plugin, but they didn't have any issues. Also, so there is an amount of factions, I have 26 factions on my server, and we are timing out too??

**Comment by mrtortillachip** [comment]
How come I have a server with 22 players max and this issue is still possible please come up with some sort of patch :)

**Comment by mrtortillachip** [comment]
atleast prevent it from crashing the server

**Comment by Zazalanz** [comment]
I don't get this ?

**Comment by ScampiFly** [comment]
I play frequently, and this issue shouldn't be occurring, this is unfair and /f show is essential to the factions experience.

**Comment by DivinityCraft** [comment]
We are admins, not devs. We can't fix this ourselves but we have paid you to give you the features you promised and those features included conversion from Factions 1.6.9.5. Please just solve this problem so that this promised feature works as intended. Mojang is not going to do anything to solve it, only you can.

**Comment by drtshock** [comment]
The feature works as intended. Your issue is that you are sending too many requests at Mojang.

**Comment by DivinityCraft** [comment]
Then make the plugin send the requests slower or something. Come up with a solution instead of saying "Nope, not gonna help you." to people who have paid money for this promised feature and then blame Mojang.

**Comment by EmilKnudsen** [comment]
Yeah, you said that twice. Seems like you wont tell us how to fix the issue?

**Comment by mrtortillachip** [comment]
Excuse me,? We are sending to many packets? But a server with 600 player dosent not to mention. YOUR plugin we paid for is sending the packets, we are just using the commands that are SUPPOSED to be working. I don't consider crashing the server working

**Comment by zippyjasmine** [comment]
I would like to start this off by stating that we are paying for this plugin, and it is not just some plugin we have found on the internet and downloaded. We are paying for this plugin so we would like for it not to crash the server, also, a server with 600 players does not "send too many packets", so how does this work out? We paid for this plugin to work. We paid for all of the features of this plugin, and we did not pay for some commands not to work, please solve this issue.

**Comment by Karen1234** [comment]
Hello!

Well I have the EXACT same issue. It crashes the server. As Zippy stated it, this is not just some plugin we have found on the internet and download. We are paying for this plugin. Therefore we expect it to work. 
I run a graphic design "bussines" and let's say I make a vector design for a client and they are not able to open it. Then I'll fix the issue because otherwise they aren't getting what they are paying for! Two very different cases, I know but the main idea is the same.

If what you say by that we are sending too many requests at Mojang is true (which I'll assume even though I highly disagree, due to the fact I can't see anything that should back up that theory) then it's really up to you to make sure your clients get a decent "product". And a decent "product" is not one that crashes your server just like that. 

Your clients expect that everything in the plugin works properly, I don't see crashing the server as "working properly". 

If it takes that little to make your plugin stop working properly then there's something wrong. 
If this was just a plugin we had downloaded free somewhere on the internet, then ok fair enough that it doesn't work. However, we are paying for this so we expect EVERY feature of this to work properly (by that I mean not crashing the server, stating the obvious of course but with this discussion I feel it's necessary).

All we ask is that you come up with a fix to this issue. Unless you can give me some pure evidence that this issue is not the plugin's fault I'd say it's up to you to fix. This is a product that should work but doesn't and you need to fix this for your paying clients.

**Comment by cnr** [comment]
Hi there. I've pushed a fix for this issue, and a new snapshot can be found [on the CI](https://ci.drtshock.net/job/FactionsUUID/)

**Comment by EmilKnudsen** [comment]
Thanks, looks like it was an issue in your plugin ?

**Comment by Karen1234** [comment]
Thank you! Well I'm glad you guys realized that it was an issue with your plugin.

**Comment by Kakifrucht** [comment]
Well, it was not exactly an issue from his side, as he said, it was your server doing too many requests ( he did not lie), but it surely was something he could have improved from the plugins side. If you check the commit you can see that only one line was changed.

**Comment by EmilKnudsen** [comment]
Another suggestion, when you're invincible you Can still see the player name tag

**Comment by cnr** [comment]
> If you check the commit you can see that only one line was changed

That one line was the source of hundreds of requests[0], when the plugin otherwise makes no requests at all[1].

Regardless, I apologize that this wasn't found and addressed sooner.

---

<sup>[0]: more specifically, one request for each player in the `target` faction each time `/f show` was used 
[1]: except in a specific case when a server upgrades from [a very old version](https://github.com/drtshock/Factions/commit/c1752477c7395c17d8c6db7749e6471fa98693e3), and there'll be _at most_ one request per player (in the _worst_ case)</sup>

**Comment by drtshock** [comment]
Still appears to be having some lag on my server. I reverted to the very old f show before tooltips or anything and it's better.

**Comment by drtshock** [comment]
Looks like I recreated this issue myself. I found out what it was and fixed it again... _hangs head in shame_
https://github.com/drtshock/Factions/commit/d0b514eff6eaeac5466cc9543ace47556836f69d#diff-dba339e247b7e8d53bc67d10f53caf97L517
